# Generated by Django 5.0.1 on 2025-02-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='endomarketingstock',
            name='location',
            field=models.CharField(choices=[('SP', 'São Paulo'), ('FOR', 'Fortaleza'), ('EUS', 'Eusébio')], default='FOR', max_length=10, verbose_name='Localização'),
        ),
    ]
