# Generated by Django 5.0.1 on 2025-02-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_alter_actionsstock_unit_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSuppliesStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Produto')),
                ('current_quantity', models.PositiveIntegerField(verbose_name='Quantidade Atual')),
                ('specification', models.TextField(blank=True, verbose_name='Especificação')),
                ('minimum_quantity', models.PositiveIntegerField(verbose_name='Quant. Mín')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Unitário (R$)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('last_update_display', models.CharField(blank=True, max_length=20, verbose_name='Última Modificação')),
                ('image', models.ImageField(blank=True, help_text='O tamanho recomendado para a imagem é quadrado (ex: 500x500 px).', null=True, upload_to='stock_images/', verbose_name='Foto do Item')),
            ],
            options={
                'verbose_name': 'Suprimentos Gerais',
                'verbose_name_plural': 'Suprimentos Gerais',
            },
        ),
        migrations.DeleteModel(
            name='CleaningProductsStock',
        ),
        migrations.AlterField(
            model_name='actionsstock',
            name='image',
            field=models.ImageField(blank=True, help_text='O tamanho recomendado para a imagem é quadrado (ex: 500x500 px).', null=True, upload_to='stock_images/', verbose_name='Foto do Item'),
        ),
        migrations.AlterField(
            model_name='endomarketingstock',
            name='image',
            field=models.ImageField(blank=True, help_text='O tamanho recomendado para a imagem é quadrado (ex: 500x500 px).', null=True, upload_to='stock_images/', verbose_name='Foto do Item'),
        ),
    ]
