# Generated by Django 5.0.1 on 2025-02-12 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_generalsuppliesstock_delete_cleaningproductsstock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsuppliesstock',
            name='location',
            field=models.CharField(choices=[('SP', 'São Paulo'), ('FOR', 'Fortaleza'), ('EUS', 'Eusébio')], default='FOR', max_length=10, verbose_name='Localização'),
        ),
    ]
